# If you change this file, please restart the server process.

# Site settings
title: Tarantino Film's
email: kevinramos456@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Página Web donde se describen i puntuan varias peliculas
  de Quentin Tarantino, uno de los directores más famosos de
  nuestra epoca, también conocido por hacer de guionista, actor y 
  productor en muchos de sus films. 
url: "http://kevinra15.github.io/"
facebook_username: QTarantino
twitter_username: QTarantino
github_username:  kevinra15

# Build settings
markdown: kramdown

#My collections
collections:
  #Sites on the headbar
  headbar:
    output: true
    permalink: /awesome/_headbar/
    url: /awesome/_headbar/my_page
