# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tarantino Film's
email: kevinramos456@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Página Web donde se describen i puntuan varias peliculas
  de Quentin Tarantino, uno de los directores más famosos de
  nuestra epoca, también conocido por hacer de guionista, actor y 
  productor en muchos de sus films. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kevinra15.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  kevinra15

# Build settings
markdown: kramdown
